# Generated by Django 4.2.5 on 2024-01-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
